/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  Contract,
  ContractState,
  TestContractResult,
  HexString,
  ContractFactory,
  SubscribeOptions,
  EventSubscription,
  CallContractParams,
  CallContractResult,
  TestContractParams,
  ContractEvent,
  subscribeContractEvent,
  subscribeContractEvents,
  testMethod,
  callMethod,
  multicallMethods,
  fetchContractState,
  ContractInstance,
  getContractEventsCurrentCount,
} from "@alephium/web3";
import { default as FullMathTestContractJson } from "../examples/full_math_test.ral.json";

// Custom types for the contract
export namespace FullMathTestTypes {
  export type State = Omit<ContractState<any>, "fields">;

  export interface CallMethodTable {
    fullMul: {
      params: CallContractParams<{ x: bigint; y: bigint }>;
      result: CallContractResult<[bigint, bigint]>;
    };
    mulDiv: {
      params: CallContractParams<{ a: bigint; b: bigint; denominator: bigint }>;
      result: CallContractResult<bigint>;
    };
    mul: {
      params: CallContractParams<{ x: bigint; y: bigint }>;
      result: CallContractResult<bigint>;
    };
    fraction: {
      params: CallContractParams<{ numerator: bigint; denominator: bigint }>;
      result: CallContractResult<bigint>;
    };
  }
  export type CallMethodParams<T extends keyof CallMethodTable> =
    CallMethodTable[T]["params"];
  export type CallMethodResult<T extends keyof CallMethodTable> =
    CallMethodTable[T]["result"];
  export type MultiCallParams = Partial<{
    [Name in keyof CallMethodTable]: CallMethodTable[Name]["params"];
  }>;
  export type MultiCallResults<T extends MultiCallParams> = {
    [MaybeName in keyof T]: MaybeName extends keyof CallMethodTable
      ? CallMethodTable[MaybeName]["result"]
      : undefined;
  };
}

class Factory extends ContractFactory<FullMathTestInstance, {}> {
  at(address: string): FullMathTestInstance {
    return new FullMathTestInstance(address);
  }

  async testSubMethod(
    params: Omit<
      TestContractParams<never, { a: bigint; b: bigint }>,
      "initialFields"
    >
  ): Promise<TestContractResult<bigint>> {
    return testMethod(this, "sub", params);
  }

  async testFullMulMethod(
    params: Omit<
      TestContractParams<never, { x: bigint; y: bigint }>,
      "initialFields"
    >
  ): Promise<TestContractResult<[bigint, bigint]>> {
    return testMethod(this, "fullMul", params);
  }

  async testMulDivMethod(
    params: Omit<
      TestContractParams<never, { a: bigint; b: bigint; denominator: bigint }>,
      "initialFields"
    >
  ): Promise<TestContractResult<bigint>> {
    return testMethod(this, "mulDiv", params);
  }

  async testMulMethod(
    params: Omit<
      TestContractParams<never, { x: bigint; y: bigint }>,
      "initialFields"
    >
  ): Promise<TestContractResult<bigint>> {
    return testMethod(this, "mul", params);
  }

  async testFractionMethod(
    params: Omit<
      TestContractParams<never, { numerator: bigint; denominator: bigint }>,
      "initialFields"
    >
  ): Promise<TestContractResult<bigint>> {
    return testMethod(this, "fraction", params);
  }
}

// Use this object to test and deploy the contract
export const FullMathTest = new Factory(
  Contract.fromJson(
    FullMathTestContractJson,
    "",
    "2a3fce94dfe5d0d5cde01623512a16cb7939ea3b2faf0931cab0b74ed887df4f"
  )
);

// Use this class to interact with the blockchain
export class FullMathTestInstance extends ContractInstance {
  constructor(address: Address) {
    super(address);
  }

  async fetchState(): Promise<FullMathTestTypes.State> {
    return fetchContractState(FullMathTest, this);
  }

  async callFullMulMethod(
    params: FullMathTestTypes.CallMethodParams<"fullMul">
  ): Promise<FullMathTestTypes.CallMethodResult<"fullMul">> {
    return callMethod(FullMathTest, this, "fullMul", params);
  }

  async callMulDivMethod(
    params: FullMathTestTypes.CallMethodParams<"mulDiv">
  ): Promise<FullMathTestTypes.CallMethodResult<"mulDiv">> {
    return callMethod(FullMathTest, this, "mulDiv", params);
  }

  async callMulMethod(
    params: FullMathTestTypes.CallMethodParams<"mul">
  ): Promise<FullMathTestTypes.CallMethodResult<"mul">> {
    return callMethod(FullMathTest, this, "mul", params);
  }

  async callFractionMethod(
    params: FullMathTestTypes.CallMethodParams<"fraction">
  ): Promise<FullMathTestTypes.CallMethodResult<"fraction">> {
    return callMethod(FullMathTest, this, "fraction", params);
  }

  async multicall<Calls extends FullMathTestTypes.MultiCallParams>(
    calls: Calls
  ): Promise<FullMathTestTypes.MultiCallResults<Calls>> {
    return (await multicallMethods(
      FullMathTest,
      this,
      calls
    )) as FullMathTestTypes.MultiCallResults<Calls>;
  }
}
