/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  ExecuteScriptParams,
  ExecuteScriptResult,
  Script,
  SignerProvider,
  HexString,
} from "@alephium/web3";
import { default as AddLiquidityScriptJson } from "../scripts/AddLiquidity.ral.json";
import { default as CreatePairScriptJson } from "../scripts/CreatePair.ral.json";
import { default as EnableFeeCollectorScriptJson } from "../scripts/EnableFeeCollector.ral.json";
import { default as RemoveLiquidityScriptJson } from "../scripts/RemoveLiquidity.ral.json";
import { default as SetFeeCollectorFactoryScriptJson } from "../scripts/SetFeeCollectorFactory.ral.json";
import { default as SwapMaxInScriptJson } from "../scripts/SwapMaxIn.ral.json";
import { default as SwapMinOutScriptJson } from "../scripts/SwapMinOut.ral.json";
import { default as GetTokenScriptJson } from "../test/GetToken.ral.json";

export namespace AddLiquidity {
  export async function execute(
    signer: SignerProvider,
    params: ExecuteScriptParams<{
      sender: Address;
      router: HexString;
      pair: HexString;
      amount0Desired: bigint;
      amount1Desired: bigint;
      amount0Min: bigint;
      amount1Min: bigint;
      deadline: bigint;
    }>
  ): Promise<ExecuteScriptResult> {
    const signerParams = await script.txParamsForExecution(signer, params);
    return await signer.signAndSubmitExecuteScriptTx(signerParams);
  }

  export const script = Script.fromJson(AddLiquidityScriptJson);
}

export namespace CreatePair {
  export async function execute(
    signer: SignerProvider,
    params: ExecuteScriptParams<{
      payer: Address;
      factory: HexString;
      alphAmount: bigint;
      tokenAId: HexString;
      tokenBId: HexString;
    }>
  ): Promise<ExecuteScriptResult> {
    const signerParams = await script.txParamsForExecution(signer, params);
    return await signer.signAndSubmitExecuteScriptTx(signerParams);
  }

  export const script = Script.fromJson(CreatePairScriptJson);
}

export namespace EnableFeeCollector {
  export async function execute(
    signer: SignerProvider,
    params: ExecuteScriptParams<{
      tokenPairFactory: HexString;
      tokenPair: HexString;
    }>
  ): Promise<ExecuteScriptResult> {
    const signerParams = await script.txParamsForExecution(signer, params);
    return await signer.signAndSubmitExecuteScriptTx(signerParams);
  }

  export const script = Script.fromJson(EnableFeeCollectorScriptJson);
}

export namespace RemoveLiquidity {
  export async function execute(
    signer: SignerProvider,
    params: ExecuteScriptParams<{
      sender: Address;
      router: HexString;
      pairId: HexString;
      liquidity: bigint;
      amount0Min: bigint;
      amount1Min: bigint;
      deadline: bigint;
    }>
  ): Promise<ExecuteScriptResult> {
    const signerParams = await script.txParamsForExecution(signer, params);
    return await signer.signAndSubmitExecuteScriptTx(signerParams);
  }

  export const script = Script.fromJson(RemoveLiquidityScriptJson);
}

export namespace SetFeeCollectorFactory {
  export async function execute(
    signer: SignerProvider,
    params: ExecuteScriptParams<{
      tokenPairFactory: HexString;
      feeCollectorFactory: HexString;
    }>
  ): Promise<ExecuteScriptResult> {
    const signerParams = await script.txParamsForExecution(signer, params);
    return await signer.signAndSubmitExecuteScriptTx(signerParams);
  }

  export const script = Script.fromJson(SetFeeCollectorFactoryScriptJson);
}

export namespace SwapMaxIn {
  export async function execute(
    signer: SignerProvider,
    params: ExecuteScriptParams<{
      sender: Address;
      router: HexString;
      pair: HexString;
      tokenInId: HexString;
      amountInMax: bigint;
      amountOut: bigint;
      deadline: bigint;
    }>
  ): Promise<ExecuteScriptResult> {
    const signerParams = await script.txParamsForExecution(signer, params);
    return await signer.signAndSubmitExecuteScriptTx(signerParams);
  }

  export const script = Script.fromJson(SwapMaxInScriptJson);
}

export namespace SwapMinOut {
  export async function execute(
    signer: SignerProvider,
    params: ExecuteScriptParams<{
      sender: Address;
      router: HexString;
      pair: HexString;
      tokenInId: HexString;
      amountIn: bigint;
      amountOutMin: bigint;
      deadline: bigint;
    }>
  ): Promise<ExecuteScriptResult> {
    const signerParams = await script.txParamsForExecution(signer, params);
    return await signer.signAndSubmitExecuteScriptTx(signerParams);
  }

  export const script = Script.fromJson(SwapMinOutScriptJson);
}

export namespace GetToken {
  export async function execute(
    signer: SignerProvider,
    params: ExecuteScriptParams<{
      token: HexString;
      sender: Address;
      amount: bigint;
    }>
  ): Promise<ExecuteScriptResult> {
    const signerParams = await script.txParamsForExecution(signer, params);
    return await signer.signAndSubmitExecuteScriptTx(signerParams);
  }

  export const script = Script.fromJson(GetTokenScriptJson);
}
