/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  ExecuteScriptParams,
  ExecuteScriptResult,
  Script,
  SignerProvider,
  HexString,
} from "@alephium/web3";
import { default as AddLiquidityScriptJson } from "../scripts/add_liquidity.ral.json";
import { default as CreatePairScriptJson } from "../scripts/create_pair.ral.json";
import { default as RemoveLiquidityScriptJson } from "../scripts/remove_liquidity.ral.json";
import { default as SwapMaxInScriptJson } from "../scripts/swap_max_in.ral.json";
import { default as SwapMinOutScriptJson } from "../scripts/swap_min_out.ral.json";
import { default as GetTokenScriptJson } from "../test/get_token.ral.json";

export namespace AddLiquidity {
  export async function execute(
    signer: SignerProvider,
    params: ExecuteScriptParams<{
      sender: Address;
      router: HexString;
      pair: HexString;
      amount0Desired: bigint;
      amount1Desired: bigint;
      amount0Min: bigint;
      amount1Min: bigint;
      deadline: bigint;
    }>
  ): Promise<ExecuteScriptResult> {
    const signerParams = await script.txParamsForExecution(signer, params);
    return await signer.signAndSubmitExecuteScriptTx(signerParams);
  }

  export const script = Script.fromJson(AddLiquidityScriptJson);
}

export namespace CreatePair {
  export async function execute(
    signer: SignerProvider,
    params: ExecuteScriptParams<{
      payer: Address;
      factory: HexString;
      alphAmount: bigint;
      tokenAId: HexString;
      tokenBId: HexString;
    }>
  ): Promise<ExecuteScriptResult> {
    const signerParams = await script.txParamsForExecution(signer, params);
    return await signer.signAndSubmitExecuteScriptTx(signerParams);
  }

  export const script = Script.fromJson(CreatePairScriptJson);
}

export namespace RemoveLiquidity {
  export async function execute(
    signer: SignerProvider,
    params: ExecuteScriptParams<{
      sender: Address;
      router: HexString;
      pairId: HexString;
      liquidity: bigint;
      amount0Min: bigint;
      amount1Min: bigint;
      deadline: bigint;
    }>
  ): Promise<ExecuteScriptResult> {
    const signerParams = await script.txParamsForExecution(signer, params);
    return await signer.signAndSubmitExecuteScriptTx(signerParams);
  }

  export const script = Script.fromJson(RemoveLiquidityScriptJson);
}

export namespace SwapMaxIn {
  export async function execute(
    signer: SignerProvider,
    params: ExecuteScriptParams<{
      sender: Address;
      router: HexString;
      pair: HexString;
      tokenInId: HexString;
      amountInMax: bigint;
      amountOut: bigint;
      deadline: bigint;
    }>
  ): Promise<ExecuteScriptResult> {
    const signerParams = await script.txParamsForExecution(signer, params);
    return await signer.signAndSubmitExecuteScriptTx(signerParams);
  }

  export const script = Script.fromJson(SwapMaxInScriptJson);
}

export namespace SwapMinOut {
  export async function execute(
    signer: SignerProvider,
    params: ExecuteScriptParams<{
      sender: Address;
      router: HexString;
      pair: HexString;
      tokenInId: HexString;
      amountIn: bigint;
      amountOutMin: bigint;
      deadline: bigint;
    }>
  ): Promise<ExecuteScriptResult> {
    const signerParams = await script.txParamsForExecution(signer, params);
    return await signer.signAndSubmitExecuteScriptTx(signerParams);
  }

  export const script = Script.fromJson(SwapMinOutScriptJson);
}

export namespace GetToken {
  export async function execute(
    signer: SignerProvider,
    params: ExecuteScriptParams<{
      token: HexString;
      sender: Address;
      amount: bigint;
    }>
  ): Promise<ExecuteScriptResult> {
    const signerParams = await script.txParamsForExecution(signer, params);
    return await signer.signAndSubmitExecuteScriptTx(signerParams);
  }

  export const script = Script.fromJson(GetTokenScriptJson);
}
