/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  Contract,
  ContractState,
  TestContractResult,
  HexString,
  ContractFactory,
  SubscribeOptions,
  EventSubscription,
  CallContractParams,
  CallContractResult,
  TestContractParams,
  ContractEvent,
  subscribeContractEvent,
  subscribeContractEvents,
  testMethod,
  callMethod,
  multicallMethods,
  fetchContractState,
  ContractInstance,
  getContractEventsCurrentCount,
} from "@alephium/web3";
import { default as TokenPairContractJson } from "../dex/token_pair.ral.json";

// Custom types for the contract
export namespace TokenPairTypes {
  export type Fields = {
    token0Id: HexString;
    token1Id: HexString;
    reserve0: bigint;
    reserve1: bigint;
    blockTimeStampLast: bigint;
    price0CumulativeLast: bigint;
    price1CumulativeLast: bigint;
    totalSupply: bigint;
  };

  export type State = ContractState<Fields>;

  export type MintEvent = ContractEvent<{
    sender: HexString;
    amount0: bigint;
    amount1: bigint;
    liquidity: bigint;
  }>;
  export type BurnEvent = ContractEvent<{
    sender: HexString;
    amount0: bigint;
    amount1: bigint;
    liquidity: bigint;
  }>;
  export type SwapEvent = ContractEvent<{
    sender: HexString;
    amount0In: bigint;
    amount1In: bigint;
    amount0Out: bigint;
    amount1Out: bigint;
    to: HexString;
  }>;

  export interface CallMethodTable {
    getSymbol: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<HexString>;
    };
    getName: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<HexString>;
    };
    getDecimals: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<bigint>;
    };
    getTotalSupply: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<bigint>;
    };
    uqdiv: {
      params: CallContractParams<{ a: bigint; b: bigint }>;
      result: CallContractResult<bigint>;
    };
    sqrt: {
      params: CallContractParams<{ y: bigint }>;
      result: CallContractResult<bigint>;
    };
    getTokenPair: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<[HexString, HexString]>;
    };
    getReserves: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<[bigint, bigint]>;
    };
    getBlockTimeStampLast: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<bigint>;
    };
    getPrice0CumulativeLast: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<bigint>;
    };
    getPrice1CumulativeLast: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<bigint>;
    };
    mint: {
      params: CallContractParams<{
        sender: HexString;
        amount0: bigint;
        amount1: bigint;
      }>;
      result: CallContractResult<bigint>;
    };
    burn: {
      params: CallContractParams<{ sender: HexString; liquidity: bigint }>;
      result: CallContractResult<[bigint, bigint]>;
    };
  }
  export type CallMethodParams<T extends keyof CallMethodTable> =
    CallMethodTable[T]["params"];
  export type CallMethodResult<T extends keyof CallMethodTable> =
    CallMethodTable[T]["result"];
  export type MultiCallParams = Partial<{
    [Name in keyof CallMethodTable]: CallMethodTable[Name]["params"];
  }>;
  export type MultiCallResults<T extends MultiCallParams> = {
    [MaybeName in keyof T]: MaybeName extends keyof CallMethodTable
      ? CallMethodTable[MaybeName]["result"]
      : undefined;
  };
}

class Factory extends ContractFactory<
  TokenPairInstance,
  TokenPairTypes.Fields
> {
  at(address: string): TokenPairInstance {
    return new TokenPairInstance(address);
  }

  async testGetSymbolMethod(
    params: Omit<TestContractParams<TokenPairTypes.Fields, never>, "testArgs">
  ): Promise<TestContractResult<HexString>> {
    return testMethod(this, "getSymbol", params);
  }

  async testGetNameMethod(
    params: Omit<TestContractParams<TokenPairTypes.Fields, never>, "testArgs">
  ): Promise<TestContractResult<HexString>> {
    return testMethod(this, "getName", params);
  }

  async testGetDecimalsMethod(
    params: Omit<TestContractParams<TokenPairTypes.Fields, never>, "testArgs">
  ): Promise<TestContractResult<bigint>> {
    return testMethod(this, "getDecimals", params);
  }

  async testGetTotalSupplyMethod(
    params: Omit<TestContractParams<TokenPairTypes.Fields, never>, "testArgs">
  ): Promise<TestContractResult<bigint>> {
    return testMethod(this, "getTotalSupply", params);
  }

  async testUqdivMethod(
    params: TestContractParams<TokenPairTypes.Fields, { a: bigint; b: bigint }>
  ): Promise<TestContractResult<bigint>> {
    return testMethod(this, "uqdiv", params);
  }

  async testSqrtMethod(
    params: TestContractParams<TokenPairTypes.Fields, { y: bigint }>
  ): Promise<TestContractResult<bigint>> {
    return testMethod(this, "sqrt", params);
  }

  async testGetTokenPairMethod(
    params: Omit<TestContractParams<TokenPairTypes.Fields, never>, "testArgs">
  ): Promise<TestContractResult<[HexString, HexString]>> {
    return testMethod(this, "getTokenPair", params);
  }

  async testGetReservesMethod(
    params: Omit<TestContractParams<TokenPairTypes.Fields, never>, "testArgs">
  ): Promise<TestContractResult<[bigint, bigint]>> {
    return testMethod(this, "getReserves", params);
  }

  async testGetBlockTimeStampLastMethod(
    params: Omit<TestContractParams<TokenPairTypes.Fields, never>, "testArgs">
  ): Promise<TestContractResult<bigint>> {
    return testMethod(this, "getBlockTimeStampLast", params);
  }

  async testGetPrice0CumulativeLastMethod(
    params: Omit<TestContractParams<TokenPairTypes.Fields, never>, "testArgs">
  ): Promise<TestContractResult<bigint>> {
    return testMethod(this, "getPrice0CumulativeLast", params);
  }

  async testGetPrice1CumulativeLastMethod(
    params: Omit<TestContractParams<TokenPairTypes.Fields, never>, "testArgs">
  ): Promise<TestContractResult<bigint>> {
    return testMethod(this, "getPrice1CumulativeLast", params);
  }

  async testUpdateMethod(
    params: TestContractParams<
      TokenPairTypes.Fields,
      { newReserve0: bigint; newReserve1: bigint }
    >
  ): Promise<TestContractResult<null>> {
    return testMethod(this, "update", params);
  }

  async testMintMethod(
    params: TestContractParams<
      TokenPairTypes.Fields,
      { sender: HexString; amount0: bigint; amount1: bigint }
    >
  ): Promise<TestContractResult<bigint>> {
    return testMethod(this, "mint", params);
  }

  async testBurnMethod(
    params: TestContractParams<
      TokenPairTypes.Fields,
      { sender: HexString; liquidity: bigint }
    >
  ): Promise<TestContractResult<[bigint, bigint]>> {
    return testMethod(this, "burn", params);
  }

  async testSwapMethod(
    params: TestContractParams<
      TokenPairTypes.Fields,
      {
        sender: HexString;
        to: HexString;
        amount0In: bigint;
        amount1In: bigint;
        amount0Out: bigint;
        amount1Out: bigint;
      }
    >
  ): Promise<TestContractResult<null>> {
    return testMethod(this, "swap", params);
  }
}

// Use this object to test and deploy the contract
export const TokenPair = new Factory(
  Contract.fromJson(
    TokenPairContractJson,
    "",
    "2569e7cf13f9cc0870412cf91babccd289e2d909b0a23efbb2ac9549ea4f1659"
  )
);

// Use this class to interact with the blockchain
export class TokenPairInstance extends ContractInstance {
  constructor(address: Address) {
    super(address);
  }

  async fetchState(): Promise<TokenPairTypes.State> {
    return fetchContractState(TokenPair, this);
  }

  async getContractEventsCurrentCount(): Promise<number> {
    return getContractEventsCurrentCount(this.address);
  }

  subscribeMintEvent(
    options: SubscribeOptions<TokenPairTypes.MintEvent>,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvent(
      TokenPair.contract,
      this,
      options,
      "Mint",
      fromCount
    );
  }

  subscribeBurnEvent(
    options: SubscribeOptions<TokenPairTypes.BurnEvent>,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvent(
      TokenPair.contract,
      this,
      options,
      "Burn",
      fromCount
    );
  }

  subscribeSwapEvent(
    options: SubscribeOptions<TokenPairTypes.SwapEvent>,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvent(
      TokenPair.contract,
      this,
      options,
      "Swap",
      fromCount
    );
  }

  subscribeAllEvents(
    options: SubscribeOptions<
      | TokenPairTypes.MintEvent
      | TokenPairTypes.BurnEvent
      | TokenPairTypes.SwapEvent
    >,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvents(
      TokenPair.contract,
      this,
      options,
      fromCount
    );
  }

  async callGetSymbolMethod(
    params?: TokenPairTypes.CallMethodParams<"getSymbol">
  ): Promise<TokenPairTypes.CallMethodResult<"getSymbol">> {
    return callMethod(
      TokenPair,
      this,
      "getSymbol",
      params === undefined ? {} : params
    );
  }

  async callGetNameMethod(
    params?: TokenPairTypes.CallMethodParams<"getName">
  ): Promise<TokenPairTypes.CallMethodResult<"getName">> {
    return callMethod(
      TokenPair,
      this,
      "getName",
      params === undefined ? {} : params
    );
  }

  async callGetDecimalsMethod(
    params?: TokenPairTypes.CallMethodParams<"getDecimals">
  ): Promise<TokenPairTypes.CallMethodResult<"getDecimals">> {
    return callMethod(
      TokenPair,
      this,
      "getDecimals",
      params === undefined ? {} : params
    );
  }

  async callGetTotalSupplyMethod(
    params?: TokenPairTypes.CallMethodParams<"getTotalSupply">
  ): Promise<TokenPairTypes.CallMethodResult<"getTotalSupply">> {
    return callMethod(
      TokenPair,
      this,
      "getTotalSupply",
      params === undefined ? {} : params
    );
  }

  async callUqdivMethod(
    params: TokenPairTypes.CallMethodParams<"uqdiv">
  ): Promise<TokenPairTypes.CallMethodResult<"uqdiv">> {
    return callMethod(TokenPair, this, "uqdiv", params);
  }

  async callSqrtMethod(
    params: TokenPairTypes.CallMethodParams<"sqrt">
  ): Promise<TokenPairTypes.CallMethodResult<"sqrt">> {
    return callMethod(TokenPair, this, "sqrt", params);
  }

  async callGetTokenPairMethod(
    params?: TokenPairTypes.CallMethodParams<"getTokenPair">
  ): Promise<TokenPairTypes.CallMethodResult<"getTokenPair">> {
    return callMethod(
      TokenPair,
      this,
      "getTokenPair",
      params === undefined ? {} : params
    );
  }

  async callGetReservesMethod(
    params?: TokenPairTypes.CallMethodParams<"getReserves">
  ): Promise<TokenPairTypes.CallMethodResult<"getReserves">> {
    return callMethod(
      TokenPair,
      this,
      "getReserves",
      params === undefined ? {} : params
    );
  }

  async callGetBlockTimeStampLastMethod(
    params?: TokenPairTypes.CallMethodParams<"getBlockTimeStampLast">
  ): Promise<TokenPairTypes.CallMethodResult<"getBlockTimeStampLast">> {
    return callMethod(
      TokenPair,
      this,
      "getBlockTimeStampLast",
      params === undefined ? {} : params
    );
  }

  async callGetPrice0CumulativeLastMethod(
    params?: TokenPairTypes.CallMethodParams<"getPrice0CumulativeLast">
  ): Promise<TokenPairTypes.CallMethodResult<"getPrice0CumulativeLast">> {
    return callMethod(
      TokenPair,
      this,
      "getPrice0CumulativeLast",
      params === undefined ? {} : params
    );
  }

  async callGetPrice1CumulativeLastMethod(
    params?: TokenPairTypes.CallMethodParams<"getPrice1CumulativeLast">
  ): Promise<TokenPairTypes.CallMethodResult<"getPrice1CumulativeLast">> {
    return callMethod(
      TokenPair,
      this,
      "getPrice1CumulativeLast",
      params === undefined ? {} : params
    );
  }

  async callMintMethod(
    params: TokenPairTypes.CallMethodParams<"mint">
  ): Promise<TokenPairTypes.CallMethodResult<"mint">> {
    return callMethod(TokenPair, this, "mint", params);
  }

  async callBurnMethod(
    params: TokenPairTypes.CallMethodParams<"burn">
  ): Promise<TokenPairTypes.CallMethodResult<"burn">> {
    return callMethod(TokenPair, this, "burn", params);
  }

  async multicall<Calls extends TokenPairTypes.MultiCallParams>(
    calls: Calls
  ): Promise<TokenPairTypes.MultiCallResults<Calls>> {
    return (await multicallMethods(
      TokenPair,
      this,
      calls
    )) as TokenPairTypes.MultiCallResults<Calls>;
  }
}
